POST http://localhost:3333/auth/signin
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###

POST http://localhost:3333/events
Content-Type: application/json

{
  "short_description": "",
  "content": "",
  "organizer": "",
  "techs": [""],
  "start_date": "",
  "end_date": ""
}

###

GET http://localhost:3333/events